#pragma once
#include "driver/gpio.h"

#define PWM_FREQUENCY 1000
#define PWM_RESOLUTION LEDC_TIMER_8_BIT
#define PWM_DUTY_CYCLE 200

#define MOTOR_AIN1  GPIO_NUM_42
#define MOTOR_AIN2  GPIO_NUM_41
#define MOTOR_BIN1  GPIO_NUM_47
#define MOTOR_BIN2  GPIO_NUM_21
#define MOTOR_PWMA  GPIO_NUM_1
#define MOTOR_PWMB  GPIO_NUM_2
#define MOTOR_STBY  GPIO_NUM_14

#define CAM_PIN_PWDN    (-1)
#define CAM_PIN_RESET   (-1)
#define CAM_PIN_XCLK    GPIO_NUM_15
#define CAM_PIN_SIOD    GPIO_NUM_4
#define CAM_PIN_SIOC    GPIO_NUM_5
#define CAM_PIN_Y9      GPIO_NUM_16
#define CAM_PIN_Y8      GPIO_NUM_17
#define CAM_PIN_Y7      GPIO_NUM_18
#define CAM_PIN_Y6      GPIO_NUM_12
#define CAM_PIN_Y5      GPIO_NUM_10
#define CAM_PIN_Y4      GPIO_NUM_8
#define CAM_PIN_Y3      GPIO_NUM_9
#define CAM_PIN_Y2      GPIO_NUM_11
#define CAM_PIN_VSYNC   GPIO_NUM_6
#define CAM_PIN_HREF    GPIO_NUM_7
#define CAM_PIN_PCLK    GPIO_NUM_13

#define CAM_XCLK_FREQ   10000000
#define CAM_FRAME_SIZE  FRAMESIZE_VGA
#define CAM_JPEG_QUALITY 15
